### PR TITLE
Add comment delimiters

### LINKED ISSUE #12: No comment syntax configured
I'm noticing that if I call `comment-region` (generally invoked via `comment-dwim`/`M-;`), there is no comment syntax configured.

I don't have time right now to figure what invocation to add to the mode for that to happen. So just leaving an issue rather than what must be a rather straightforward PR.

### PR DESCRIPTION
**Pull request by aspiwack**
Closes #12.

### CODE REVIEW

**Review by yannham — APPROVED** [review]

**Comment by purcell** [comment]
You might also consider setting `comment-start-skip` to `"#+\\s-*"`.

**Comment by aspiwack** [comment]
I checked the documentation before writing my PR, and my understanding was that  `comment-start-skip` was to detect already commented bits for `comment-dwim`. I checked that `comment-dwim` worked fine (it did), so I didn't bother with `comment-start-skip`. Did I miss something?

**Comment by purcell** [comment]
Hmm, I don't know — most modes I've seen tend to set up both vars, so the cargo cult wisdom is apparently that only `comment-start` is required, but that it is Good Practice™ to set `comment-start-skip` too. I confess to being unaware of the specific reasons, if any actually exist. 😅

**Comment by aspiwack** [comment]
Ok. Then, with your permission, I'm going to Ockham-razor this one, and leave `comment-start-skip` out until something goes wrong :slightly_smiling_face: .

**Comment by purcell** [comment]
Haha, you certainly don't need my blessing to ignore this entirely for now!

**Pull request merged**
