### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by purcell**
A few little fixes and improvements here. 😁

### CODE REVIEW

**Comment by purcell** [comment]
Not done: string interpolation. I might tackle that, but it's fiddly because the interpolation depends on the `%%%` quoting level of the containing string...

**Comment by yannham** [comment]
@purcell for what it worth, in vim, I just expanded for a finite number of cases (ie `count(%) <= 4`), which will hopefully cover 99.999% of the cases (https://github.com/nickel-lang/vim-nickel/blob/main/syntax/nickel.vim#L77,L80)

**Comment by purcell** [comment]
@yannham the string quoting code here works fine for the general case, but it's the interpolation that's fiddly, because to detect it properly you have to backtrack to where the string started. It can be done efficiently in Emacs, I think, I just haven't done it here.

**Comment by purcell** [comment]
If you guys want to add me as a committer I'm happy to shepherd these changes in, and also potentially other changes. I'm a committer for a large number of Emacs-related projects across Github, e.g. haskell-mode.

**Comment by yannham** [comment]
> @yannham the string quoting code here works fine for the general case, but it's the interpolation that's fiddly, because to detect it properly you have to backtrack to where the string started. It can be done efficiently in Emacs, I think, I just haven't done it here.

I know nothing about how emacs handle that, but I wonder if the same trick could apply. The problem I had was similar, even without interpolation, because the ending delimiter depends on the start delimiter of the string. Instead of having one parametrized rule that backtracks, like `m%{n}" .\+ "%{n}`, I just expanded this rule for `n=1,2,3,4`. Maybe the same could apply as well? In that, if you have a rule with a fixed start delimiter, then the interpolation sequence is fixed as well inside this string.

**Comment by yannham** [comment]
> @yannham the string quoting code here works fine for the general case, but it's the interpolation that's fiddly, because to detect it properly you have to backtrack to where the string started. It can be done efficiently in Emacs, I think, I just haven't done it here.

You've been added with write access to the repo :slightly_smiling_face:  thanks for helping out!

**Pull request merged**
